import {ROOM_OBSTACLES,furnitureRadius,validPlacement} from './furniture-layout.js';
import {route,blocked,clearSegment} from './navigation.js';
import {poseLegs} from './cat-model.js';
import {CatWorld,THREE,C,group,ball,box,cyl,tube,torus,star,flower,plant,sign,mesh,makeCat,disposeCat} from './world.js';
import {PERSONALITIES} from './state.js';
const limit=(v,a,b)=>Math.max(a,Math.min(b,v));
export class LivingWorld extends CatWorld {
 constructor(canvas,onPet,onWardrobe,onEvent){
  super(canvas,onPet,onWardrobe);this.onEvent=onEvent;this.pos=new THREE.Vector3(0,.06,.55);this.destination=null;this.face=.35;this.gait=0;this.walkBlend=0;this.mode='free';this.inputMode=null;this.nextIdle=7;this.behavior='watch';this.poseUntil=0;this.idleCount=0;this.stats={breed:'calico',bond:0};this.props=group(this.scene);this.furnitureRoot=group(this.environments.home);this.furnitureMeshes=new Map();this.dragging=false;this.pointer=new THREE.Vector2();this.ray=new THREE.Raycaster();this.floorPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);this.buildToys();this.buildGarden();this.buildStreet();this.buildBathTools();this.buildStoryProps();this.buildTVShows();this.ready=true;this.installInput();
 }
 emit(type,data={}){this.onEvent?.(type,data);}
 setScene(name){super.setScene(name);if(!this.ready)return;this.pos.set(0,this.baseY,this.baseZ);this.destination=null;this.waypoints=[];this.jump=null;this.behavior='watch';this.poseUntil=0;this.cat.visible=true;this.nextIdle=this.elapsed+7;this.face=.35;}
 setMode(mode){this.mode=mode;this.inputMode=['wand','fetch','hide','scrub','rinse','decorate','explore'].includes(mode)?mode:null;this.controls.enabled=!this.inputMode&&!this.uiBlocked;this.canvas.style.cursor=this.inputMode?'crosshair':'grab';this.destination=null;this.waypoints=[];this.jump=null;this.afterArrive=null;this.poseUntil=0;this.cat.visible=true;this.behavior='watch';this.nextIdle=this.elapsed+7;this.toys.visible=['wand','fetch','hide'].includes(mode);this.furnitureRoot.visible=mode!=='hide';this.feather.visible=mode==='wand';this.fetchBall.visible=mode==='fetch';this.hideBoxes.visible=mode==='hide';this.sponge.visible=mode==='scrub';this.handShower.visible=mode==='rinse';this.ballPhase='ready';this.lastCatch=-10;this.lastWand=new THREE.Vector3(99,0,99);this.wandTarget=null;this.strokePrevious=null;this.bathRatio=0;this.foam.children.forEach(m=>m.visible=mode==='rinse');this.drops.visible=mode==='rinse';this.selectedFurniture=null;this.furnitureRoot.traverse(o=>{if(o.isMesh&&o.material.emissive)o.material.emissive.setHex(0);});if(mode==='hide')this.newHideRound();if(mode==='explore')this.pos.set(0,.06,1.9);this.emit('input-mode',{mode});}
 syncState(state){this.stats={breed:state.breed,bond:state.bond,fullness:state.fullness};this.setFurniture(state.furniture);}
 buildToys(){this.toys=group(this.scene);this.toys.visible=false;this.feather=group(this.toys);tube(this.feather,0x997451,[[0,0,0],[.35,.65,-.12]],.025);tube(this.feather,0xc9af86,[[.35,.65,-.12],[.13,.9,-.1],[-.12,.8,.0]],.012);for(let i=0;i<3;i++){const f=ball(this.feather,[0xa9d8ee,0xd0a982,0x9fb18d][i],[-.14+i*.055,.78,0],[.07,.19,.03]);f.rotation.z=(i-1)*.3;}this.fetchBall=ball(this.toys,0x93c2e4,[0,.2,1.9],[.13,.13,.13]);this.ballStripe=torus(this.fetchBall,0xffe4a1,[0,0,0],1.01,.06,[.5,0,.5]);this.hideBoxes=group(this.toys);for(let i=0;i<3;i++){const b=group(this.hideBoxes,[(i-1)*1.9,.03,1]);this.makeBox(b,1);b.userData.boxIndex=i;b.traverse(o=>o.userData.boxIndex=i);} }
 makeBox(g,size=1){const w=1.18*size,d=1.36*size,h=.72*size;
 box(g,0xb18c63,[0,.055,0],[w,.075,d],.015);
 for(const side of [-1,1]){box(g,0xd6b18a,[side*w*.5,h*.5,0],[.035,h,d],.008);box(g,0xd6b18a,[0,h*.5,side*d*.5],[w,h,.035],.008);const flap=box(g,0xe0bc95,[side*(w*.5+.15),h+.025,0],[.34,.028,d],.008);flap.rotation.z=side*.35;}
 box(g,0xe7cea1,[0,.39,d*.5+.022],[.17,.30,.008],.001);sign(g,'♡',[0,.39,d*.5+.031],.15,.17,'#e7cea1','#8d7250');
 }
 buildBathTools(){this.sponge=group(this.scene);box(this.sponge,0xf7cf87,[0,0,0],[.39,.2,.23],.06);for(let i=0;i<6;i++)ball(this.sponge,0xffebc2,[(i%3-.8)*.11,.1,Math.floor(i/3)*.08],[.025,.014,.025]);this.sponge.visible=false;this.handShower=group(this.scene);tube(this.handShower,0x93b9ce,[[0,0,0],[.08,-.2,0],[.2,-.35,0]],.035);cyl(this.handShower,0xa6cfe4,[0,.03,0],.14,.17,.08);this.handShower.visible=false;this.sponge.position.set(1.2,1.4,.9);this.handShower.position.set(1.1,2,.9);}
 buildGarden(){const p=this.environment('garden');cyl(p,0xb8a37f,[0,-.2,0],4.45,4.5,.4);cyl(p,0xb8c69d,[0,.02,0],4.4,4.4,.06);cyl(p,0xb1d1e3,[0,.065,-1.4],1.05,1.05,.04).scale.z=.55;torus(p,0xcab99a,[0,.065,-1.4],1.13,.09).scale.z=.6;for(let i=0;i<24;i++){const a=i*2.4,r=2.65+(i%4)*.31;const x=Math.cos(a)*r,z=Math.sin(a)*r;tube(p,0x8aa58d,[[x,0,z],[x,.47,z]],.018);flower(p,x,.51,z,i%2?0xb8c59b:0xe5c29b).scale.setScalar(.65);}for(let i=0;i<7;i++)cyl(p,0xf4e4dc,[-1.4+i*.45,.08,1.5-Math.sin(i)*.25],.27,.27,.07);plant(p,-2.9,-2.1,0xabbf9a,1.8);plant(p,2.6,-2.4,0x91a478,1.7);box(p,0xc99f72,[1.9,.6,-2.6],[1.7,.15,.5]);for(const x of [1.2,2.6])box(p,0x997451,[x,.3,-2.6],[.15,.6,.3]);sign(p,'蓝铃花园',[-1.9,1.0,-2.7],1.15,.45,'#e5dec8','#727c60');}
 buildStreet(){const p=this.environment('street');box(p,0xb5a082,[0,-.2,0],[8.9,.4,6.6],.2);box(p,0xd8cbb0,[0,.03,0],[8.7,.06,6.4]);for(let i=0;i<10;i++)box(p,0xede0c2,[-4+i*.9,.075,.35],[.04,.01,5.7],.005);for(const [x,color,label]of [[-2.8,0xb9c5a0,'花花铺'],[0,0xb5c4bf,'喵邮局'],[2.8,0xd9b494,'小鱼店']]){box(p,color,[x,1.4,-2.6],[2.3,2.8,.7],.12);box(p,0xfff1eb,[x,1.42,-2.2],[1.75,1.5,.08]);box(p,0xb6cddd,[x,1.4,-2.13],[1.55,1.28,.03]);box(p,0x99aa88,[x,2.35,-1.94],[2.4,.15,.9]);sign(p,label,[x,2.65,-2.18],1.4,.36,'#f1e5cd','#76654d');}plant(p,-3.4,1.7,0xa6bbaa,1.2);plant(p,3.4,1.5,0x9bae80,1.1);box(p,0x98bbd5,[-2.8,.68,-.6],[.55,1.25,.5]);box(p,0x657d9d,[-2.8,.93,-.335],[.34,.06,.025],.008);}


 buildTVShows(){this.tvButterfly=group(this.tv.g,[0,0,.21]);for(const side of [-1,1]){ball(this.tvButterfly,0xc1a0d8,[side*.14,0,0],[.18,.23,.025]);ball(this.tvButterfly,0xe9b6ce,[side*.12,-.14,0],[.13,.14,.025]);}ball(this.tvButterfly,0x786681,[0,0,.02],[.022,.18,.026]);this.tvBird=group(this.tv.g,[0,0,.21]);ball(this.tvBird,0x9dc6e3,[0,0,0],[.22,.17,.035]);ball(this.tvBird,0xc0dfef,[.15,.13,0],[.13,.13,.035]);const beak=mesh(this.tvBird,new THREE.ConeGeometry(.06,.14,3),0xedc180,[.28,.11,0]);beak.rotation.z=-Math.PI/2;ball(this.tvBird,0x544762,[.18,.17,.035],[.015,.018,.012]);ball(this.tvBird,0x749fbf,[-.04,.03,.036],[.12,.09,.015]);this.tvLabels=[this.tv.ticker,sign(this.tv.g,'蝶蝶频道',[.48,-.36,.16],.6,.19,'#90cde3','#5c90b0'),sign(this.tv.g,'鸟鸟频道',[.48,-.36,.16],.6,.19,'#90cde3','#5c90b0')];this.setTVChannel(0);}
 setTVChannel(channel){this.tvChannel=channel;this.tv.fish.visible=channel===0;this.tvButterfly.visible=channel===1;this.tvBird.visible=channel===2;this.tvLabels.forEach((m,i)=>m.visible=i===channel);}
 buildStoryProps(){this.carriedToy=group(this.scene);ball(this.carriedToy,0xa6c9e1,[0,0,0],[.15,.12,.12]);star(this.carriedToy,0xf6d58e,[0,0,.09],.10);this.carriedToy.visible=false;this.leafHat=group(this.scene);for(let i=0;i<3;i++){const leaf=ball(this.leafHat,[0xb5c998,0xc5b785,0x9fb99a][i],[(i-1)*.12,.02,0],[.18,.035,.1]);leaf.rotation.z=(i-1)*.23;}this.leafHat.visible=false;this.ducks=group(this.scene);for(let i=0;i<3;i++){const d=group(this.ducks,[i*.38,0,.2]);ball(d,0xf1d28c,[0,.12,0],[.14,.11,.18]);ball(d,0xf4d98e,[0,.25,.06],[.10,.10,.10]);ball(d,0xde9c75,[0,.24,.15],[.07,.024,.065]);}this.ducks.visible=false;}
 makeFurniture(id){const g=new THREE.Group();if(id==='box')this.makeBox(g);if(id==='bed'){const base=cyl(g,0xa4ae90,[0,.15,0],.65,.7,.27);base.scale.z=.75;const pad=cyl(g,0xeee0be,[0,.29,0],.55,.55,.12);pad.scale.z=.75;const rim=torus(g,0xa4ae90,[0,.36,0],.56,.095);rim.scale.z=.74;}
 if(id==='tower'){cyl(g,0xc99f72,[0,.08,0],.58,.65,.16);cyl(g,0xe7c6a6,[0,.64,0],.10,.12,1.12);cyl(g,0xc99f72,[0,1.25,0],.69,.7,.12);box(g,0xcbb998,[-.37,.67,.15],[.57,.12,.47]);for(let i=0;i<22;i++)torus(g,0xb9a789,[0,.18+i*.047,0],.103,.012);tube(g,0xb7a27c,[[.4,1.2,0],[.4,.89,0]],.014);ball(g,0x9ec9e6,[.4,.81,0],[.09,.09,.09]);}
 if(id==='rug'){const r=cyl(g,0xa6b99f,[0,.06,0],.8,.8,.05);r.scale.z=.66;torus(g,0xe3dfbd,[0,.095,0],.64,.035).scale.z=.66;}
 if(id==='toy'){ball(g,0xa6c9e1,[0,.2,0],[.22,.23,.2]);tube(g,0x997451,[[0,.2,0],[0,.8,0]],.025);const fish=ball(g,0xefc095,[0,.89,0],[.25,.12,.08]);ball(g,0x5d496b,[.12,.91,.071],[.015,.015,.015]);star(g,0xe8a9c3,[-.28,.89,0],.12);}
 g.userData.furniture=id;g.traverse(o=>o.userData.furniture=id);return g;}
 setFurniture(items){const key=JSON.stringify(items);if(key===this.furnitureKey)return;this.furnitureKey=key;for(const g of this.furnitureMeshes.values()){this.furnitureRoot.remove(g);disposeCat(g);}this.furnitureMeshes.clear();for(const item of items){const g=this.makeFurniture(item.id);g.position.set(item.x,.04,item.z);g.rotation.y=item.rotation;this.furnitureRoot.add(g);this.furnitureMeshes.set(item.id,g);} }
 selectFurniture(id){this.selectedFurniture=id;}
 placeSelected(x,z,rotation){const g=this.furnitureMeshes.get(this.selectedFurniture);if(!g)return;const nx=limit(x,-3.2,3.2),nz=limit(z,.2,2.25),items=[...this.furnitureMeshes].map(([id,m])=>({id,x:m.position.x,z:m.position.z}));if(!validPlacement({id:this.selectedFurniture,x:nx,z:nz},items,this.pos)){this.emit('placement-blocked');return;}g.position.x=nx;g.position.z=nz;if(rotation!==undefined)g.rotation.y=rotation;this.emit('place',{id:this.selectedFurniture,x:g.position.x,z:g.position.z,rotation:g.rotation.y});}
 setupExploration(outing){this.outing=outing;if(this.trail){this.scene.remove(this.trail);disposeCat(this.trail);}this.trail=group(this.scene);for(const spot of outing.spots){const g=group(this.trail,[spot.x,.05,spot.z]);cyl(g,0xa9b88f,[0,.04,0],.26,.3,.08);star(g,0xf6d986,[0,.36,0],.14);g.userData.spot=spot.id;g.traverse(o=>o.userData.spot=spot.id);}
 const b={park:'orange',garden:'blue',street:'ragdoll'}[outing.region];this.friend=makeCat(b,'bow');this.friend.scale.setScalar(.57);this.friend.position.set(2.5,.07,-.8);this.friend.rotation.y=-.5;this.friend.userData.spot='friend';this.friend.traverse(o=>o.userData.spot='friend');this.trail.add(this.friend);this.eventProp=group(this.trail,[-2.35,.1,-.85]);for(let i=0;i<5;i++){const l=ball(this.eventProp,0xd7b084,[(i%3)*.14,0,(i%2)*.2],[.18,.09,.13]);l.rotation.z=i*.5;}this.eventProp.traverse(o=>o.userData.spot='event');}
 hideSpot(id){const g=this.trail?.children.find(x=>x.userData.spot===id);if(g)g.visible=false;}
 clearExploration(){if(this.trail){this.scene.remove(this.trail);disposeCat(this.trail);this.trail=null;}this.outing=null;}
 obstacles(){
 const room=['home','tv'].includes(this.currentScene);const items=[];
 if(room){items.push(...ROOM_OBSTACLES);
  for(const [id,g]of this.furnitureMeshes)if(id!=='rug')items.push({id,type:'circle',x:g.position.x,z:g.position.z,r:furnitureRadius(id),height:id==='tower'?1.4:id==='toy'?1.0:id==='box'?.78:.42});
 }
 if(this.mode==='explore'){
  items.push({id:'friend',type:'circle',x:2.5,z:-.8,r:.70,height:1.2});
  if(this.currentScene==='garden')items.push({id:'pond',x:0,z:-1.4,w:2.1,d:1.1,height:.12},{id:'bench',x:1.9,z:-2.6,w:1.9,d:.7,height:.8},{id:'plant',type:'circle',x:-2.9,z:-2.1,r:.5,height:1.7});
  if(this.currentScene==='park')items.push(...[[-2.9,-1.8],[2.8,-2.1],[-3.4,.7]].map(([x,z])=>({id:'tree',type:'circle',x,z,r:.25,height:3})));
  if(this.currentScene==='street')items.push({id:'postbox',x:-2.8,z:-.6,w:.6,d:.55,height:1.4});
 }
 return items;
 }
 navPadding(){return this.stats.breed==='maine'?.95:.73;}
 walkRoute(x,z,after,y=.06){
 const points=route(this.pos,{x,z},this.obstacles(),undefined,this.navPadding());
 this.waypoints=points.map(p=>new THREE.Vector3(p.x,.06,p.z));this.destination=this.waypoints.shift()||null;this.behavior='walk';
 this.afterArrive=()=>{if(y>.12)this.beginJump(new THREE.Vector3(x,y,z),after);else after?.();};
 if(!this.destination){const cb=this.afterArrive;this.afterArrive=null;cb?.();}
 }
 beginJump(target,after){this.destination=null;this.jump={from:this.pos.clone(),target,start:this.elapsed,after};this.behavior='jump';}
 moveTo(x,z,after,y=.06){
 this.poseUntil=0;
 if(this.jump){this.jump.after=()=>this.walkRoute(x,z,after,y);return;}if(this.pos.y>.15){const exit=route({x:this.pos.x,z:this.pos.z},{x:this.pos.x,z:this.pos.z+1.05},this.obstacles(),undefined,this.navPadding()).at(-1);if(exit){this.beginJump(new THREE.Vector3(exit.x,.06,exit.z),()=>this.walkRoute(x,z,after,y));return;}}
 this.walkRoute(x,z,after,y);
 }
 callCat(){this.moveTo(0,1.8,()=>{this.pose('nuzzle',3);this.emit('arrived-call');});}
 useFurniture(id){const g=this.furnitureMeshes.get(id);if(!g)return;this.moveTo(g.position.x,g.position.z+(id==='box'?1.18:id==='toy'?.75:0),()=>{this.face=Math.atan2(g.position.x-this.pos.x,g.position.z-this.pos.z);this.behavior=id==='bed'?'sleep':id==='rug'?'roll':id;this.poseUntil=this.elapsed+6;this.emit('behavior',{text:{box:'纸箱就是豪宅，租金是一个呼噜。',bed:'已进入省电模式：呼噜噜。',tower:'巡视完毕，这个家没有小鱼干入侵。',rug:'把自己卷成一颗毛茸茸饭团。',toy:'这条鱼怎么打都不倒？'}[id]});},id==='tower'?1.34:id==='bed'?.39:.06);}
 pose(name,seconds=3){this.behavior=name;this.poseUntil=this.elapsed+seconds;this.destination=null;this.waypoints=[];this.afterArrive=null;}
 pointFromEvent(e,y=0){const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const p=new THREE.Vector3();this.ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-y),p);p.x=limit(p.x,-3.25,3.25);p.z=limit(p.z,-1.9,2.3);return p;}
 objectAt(e,objects){this.pointFromEvent(e);const hits=this.ray.intersectObjects(objects,true);return hits.find(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent;}return true;})?.object;}
 installInput(){this.canvas.addEventListener('pointerdown',e=>{if(this.uiBlocked)return;this.dragging=true;this.pointerStart={x:e.clientX,y:e.clientY};this.strokePrevious=null;if(this.inputMode){this.canvas.setPointerCapture(e.pointerId);this.handlePointer(e,true);} });this.canvas.addEventListener('pointermove',e=>{if(this.uiBlocked)return;if(this.dragging&&this.inputMode)this.handlePointer(e,false);});this.canvas.addEventListener('pointerup',e=>{if(this.uiBlocked)return;const moved=this.pointerStart?Math.hypot(e.clientX-this.pointerStart.x,e.clientY-this.pointerStart.y):0;this.dragging=false;this.strokePrevious=null;if(moved>9||['wand','scrub','rinse','decorate'].includes(this.mode))return;if(this.mode==='fetch'){const p=this.pointFromEvent(e);this.throwBall(p.x,p.z);}else if(this.mode==='hide'){const o=this.objectAt(e,[this.hideBoxes]);if(o?.userData.boxIndex!==undefined)this.chooseBox(o.userData.boxIndex);}else if(this.mode==='explore'){const o=this.objectAt(e,[this.trail]);if(o?.userData.spot)this.emit('visit-spot',{id:o.userData.spot});else{const p=this.pointFromEvent(e);this.moveTo(p.x,p.z);}}else if(this.mode==='free'){const o=this.objectAt(e,[this.furnitureRoot]);if(o?.userData.furniture)this.useFurniture(o.userData.furniture);}});this.canvas.addEventListener('pointercancel',()=>{this.dragging=false;this.strokePrevious=null;});}
 handlePointer(e,down){if(this.mode==='wand'){const p=this.pointFromEvent(e,.55);this.wandTarget=p;this.feather.position.set(p.x,.55,p.z);this.walkRoute(p.x,p.z);const end=this.waypoints.at(-1)||this.destination;if(end){this.wandTarget.set(end.x,.55,end.z);this.feather.position.copy(this.wandTarget);}}
 if(this.mode==='decorate'){if(down){const o=this.objectAt(e,[this.furnitureRoot]);if(o?.userData.furniture){this.selectedFurniture=o.userData.furniture;this.emit('select-furniture',{id:this.selectedFurniture});}}const p=this.pointFromEvent(e);this.placeSelected(p.x,p.z);}
 if(['scrub','rinse'].includes(this.mode)){const r=this.canvas.getBoundingClientRect();const screen=this.project(this.cat.position.clone().add(new THREE.Vector3(0,.95,.25)));const dx=e.clientX-r.left-screen.x,dy=e.clientY-r.top-screen.y;const catRadius=Math.max(40,r.height*.16);const near=dx*dx/(catRadius*catRadius)+dy*dy/(catRadius*catRadius*1.4)<1;const p=this.pointFromEvent(e,1.0);(this.mode==='scrub'?this.sponge:this.handShower).position.set(p.x,1.1,p.z+.2);if(near){const distance=this.strokePrevious?Math.hypot(e.clientX-this.strokePrevious.x,e.clientY-this.strokePrevious.y):8;if(distance>2)this.emit('bath-stroke',{amount:Math.min(distance,26)/5});this.strokePrevious={x:e.clientX,y:e.clientY};}}
 }
 bathProgress(ratio,phase){this.bathRatio=ratio;this.foam.children.forEach((m,i)=>m.visible=phase==='scrub'?i/this.foam.children.length<ratio:i/this.foam.children.length>ratio);}
 wiggleWand(){const n=(this.wandStep||0)+1;this.wandStep=n;const x=n%2?1.45:-1.45,z=n%3===0?.1:1.45;this.wandTarget=new THREE.Vector3(x,.55,z);this.feather.position.copy(this.wandTarget);this.walkRoute(x,z);const end=this.waypoints.at(-1)||this.destination;if(end){this.wandTarget.set(end.x,.55,end.z);this.feather.position.copy(this.wandTarget);}}
 throwBall(x=1.7,z=.8){if(!['ready','done'].includes(this.ballPhase))return;const points=route(this.pos,{x,z},this.obstacles(),undefined,this.navPadding()),end=points.at(-1)||{x:this.pos.x,z:this.pos.z};this.ballPhase='flying';this.ballFlight={start:this.elapsed,from:new THREE.Vector3(0,1.3,2.3),target:new THREE.Vector3(end.x,.16,end.z)};this.fetchBall.position.copy(this.ballFlight.from);this.emit('ball-thrown');this.walkRoute(end.x,end.z);}
 newHideRound(){this.hiddenBox=Math.floor(Math.random()*3);this.hideRevealed=false;this.cat.visible=false;this.hideBoxes.children.forEach(g=>g.rotation.z=0);this.emit('hide-ready');}
 chooseBox(i){if(this.hideRevealed)return;if(i===this.hiddenBox){this.hideRevealed=true;this.cat.visible=true;this.pos.set((i-1)*1.9,.57,1);this.pose('peek',2);this.emit('hide-found');}else{this.hideBoxes.children[i].rotation.z=.08;this.emit('hide-miss');}}
 hideHint(){return ['左边','中间','右边'][this.hiddenBox];}
 project(p){const v=p.clone().project(this.camera);return {x:(v.x+1)*this.canvas.clientWidth/2,y:(1-v.y)*this.canvas.clientHeight/2};}
 updateLiving(dt,t){if(!this.ready||!this.cat)return;const {rig,head,eyes,legs}=this.cat.userData;rig.scale.set(1,1,1);this.cat.visible=!(this.mode==='hide'&&!this.hideRevealed);this.props.visible=this.currentScene!=='adopt';if(this.trail)this.trail.visible=this.mode==='explore';this.carriedToy.visible=(this.mode==='free'&&this.stats.bond>=35&&['follow','gift'].includes(this.behavior));this.leafHat.visible=this.mode==='explore'&&this.behavior==='roll'&&t<this.poseUntil;this.ducks.visible=this.mode==='explore'&&this.behavior==='parade'&&t<this.poseUntil;this.tvButterfly.position.x=Math.sin(t*1.4)*.48;this.tvButterfly.position.y=Math.sin(t*2.2)*.12;this.tvButterfly.children.forEach((m,i)=>{if(i<4)m.rotation.y=Math.sin(t*10)*(i<2?1:-1)*.4;});this.tvBird.position.x=Math.sin(t)*.46;this.tvBird.position.y=Math.abs(Math.sin(t*4))*.12;const wobbleToy=this.furnitureMeshes.get('toy');if(wobbleToy)wobbleToy.rotation.z=this.behavior==='toy'&&t<this.poseUntil?Math.sin(t*7)*.12:0;if(this.action){this.emitFrame();return;}
 if(this.mode==='free'&&t>this.nextIdle&&!this.jump&&!this.destination&&t>this.poseUntil){this.nextIdle=t+10;const choices=PERSONALITIES[this.stats.breed].activities;let activity=choices[this.idleCount++%choices.length];if(this.stats.fullness<45)activity='sniff';if(this.stats.bond>=35&&this.idleCount%4===0)activity='follow';const item=[...this.furnitureMeshes.keys()].find(id=>id===activity||(activity==='sleep'&&id==='bed'));if(item)this.useFurniture(item);else {const dest={sun:[-1.25,-1.0,.07],sofa:[-2.1,-.55,.74],sleep:[1.9,1.6,.07],sniff:[.1,1.4,.06],follow:[0,1.8,.06],walk:[Math.sin(this.idleCount*2)*2.2,1+Math.cos(this.idleCount)*.8,.06],toy:[-1.25,1.65,.06],box:[1.9,1.1,.06],tower:[-2,-.5,.74]}[activity]||[0,.5,.06];this.moveTo(dest[0],dest[1],()=>{this.behavior=activity;this.poseUntil=this.elapsed+7;if(activity==='sofa'||activity==='tower')this.face=Math.PI/2;},dest[2]);this.emit('behavior',{text:{sun:'找到了阳光，正在给毛毛充电。',sofa:'沙发已被占领，请人类另找座位。',sleep:'没什么事的话，本喵先睡为敬。',sniff:'闻到了饭的方向，也可能是想象力。',follow:this.stats.bond>=35?'叼着玩具来找你了：再陪我玩一会儿嘛。':'正在认真观察你。',walk:'小屋巡逻中，检查每一块地板。',toy:'对这个毛线球发起友好挑战。'}[activity]||'正在寻找下一个快乐角落。'});}}
 if(this.jump){const j=this.jump,u=Math.min(1,(t-j.start)/.72);this.pos.lerpVectors(j.from,j.target,u);this.pos.y+=Math.sin(u*Math.PI)*.55;if(u>=1){this.jump=null;j.after?.();}}
 const wasMoving=!!this.destination;let travelled=0;
 if(this.destination){
  const delta=this.destination.clone().sub(this.pos),dist=Math.hypot(delta.x,delta.z),speed=['wand','fetch','explore'].includes(this.mode)?2.2:1.05;
  if(dist>.01){const target=Math.atan2(delta.x,delta.z);const turn=Math.atan2(Math.sin(target-this.face),Math.cos(target-this.face));this.face+=turn*Math.min(1,dt*9);}
  travelled=Math.min(dist,dt*speed);
  if(dist<dt*speed+.012){this.pos.copy(this.destination);this.destination=this.waypoints?.shift()||null;if(!this.destination){const cb=this.afterArrive;this.afterArrive=null;cb?.();}}
  else {this.pos.x+=delta.x/dist*travelled;this.pos.z+=delta.z/dist*travelled;this.pos.y+=delta.y*Math.min(1,dt*4);}
 }
 this.walkBlend=THREE.MathUtils.damp(this.walkBlend||0,wasMoving?1:0,12,dt);this.gait=(this.gait||0)+travelled/(.40*this.cat.scale.x/.64);
 rig.position.y=Math.sin(this.gait*Math.PI*4)*.012*this.walkBlend;
 rig.rotation.z=Math.sin(this.gait*Math.PI*2)*.014*this.walkBlend;
 poseLegs(this.cat,this.gait,.40*this.walkBlend,.12*this.walkBlend);
 if(this.mode==='wand'&&this.wandTarget){const d=Math.hypot(this.pos.x-this.wandTarget.x,this.pos.z-this.wandTarget.z);if(d<.34&&t-this.lastCatch>1.1&&this.lastWand.distanceTo(this.wandTarget)>.6){this.lastCatch=t;this.lastWand.copy(this.wandTarget);this.pose('pounce',.65);this.emit('wand-catch');}this.feather.rotation.z=Math.sin(t*7)*.15;}
 if(this.mode==='fetch'){
 if(this.ballPhase==='flying'){
  const flight=this.ballFlight,u=Math.min(1,(t-flight.start)/1.05);this.fetchBall.position.lerpVectors(flight.from,flight.target,u);this.fetchBall.position.y+=Math.sin(u*Math.PI)*2.4;this.fetchBall.rotation.x+=dt*7;
  if(u>=1){this.ballPhase='waiting';this.walkRoute(flight.target.x,flight.target.z);}
 }
 if(this.ballPhase==='waiting'&&Math.hypot(this.pos.x-this.fetchBall.position.x,this.pos.z-this.fetchBall.position.z)<.50){this.ballPhase='returning';const drop=route(this.pos,{x:0,z:2.05},this.obstacles(),undefined,this.navPadding()).at(-1)||this.pos;this.moveTo(drop.x,drop.z,()=>{this.ballPhase='done';this.fetchBall.position.copy(this.pos).add(new THREE.Vector3(.22,.10,.18));this.emit('fetch-return');});}
 if(this.ballPhase==='returning'){this.cat.position.copy(this.pos);this.cat.rotation.y=this.face;this.cat.updateMatrixWorld(true);this.cat.userData.mouth.getWorldPosition(this.fetchBall.position);}
 }
 if(this.mode==='hide'&&!this.hideRevealed){const b=this.hideBoxes.children[this.hiddenBox];b.rotation.z=Math.sin(t*5)*.025;}
 if(['scrub','rinse'].includes(this.mode)){this.drops.visible=this.mode==='rinse';head.rotation.z=Math.sin(t*2)*.08;this.foam.children.forEach((m,i)=>m.position.y=.67+Math.sin(t*2+i)*.07);}
 if(!this.destination&&t<this.poseUntil){if(['sleep','sofa','sun'].includes(this.behavior)){eyes.forEach(e=>e.scale.y=.1);rig.position.y=-.13;poseLegs(this.cat,0,0,0);head.rotation.z=.1;}if(this.behavior==='roll'||this.behavior==='leaves'){rig.rotation.z=Math.sin(t*3)*.9;rig.position.y=.12;}if(this.behavior==='box'){rig.position.y=-.15;poseLegs(this.cat,0,0,0);eyes.forEach(e=>e.scale.y=.8);}if(this.behavior==='tower')head.rotation.y=Math.sin(t)*.45;if(['toy','paw','sniff'].includes(this.behavior)){legs[0].rotation.x=-.8+Math.sin(t*5)*.4;head.rotation.x=.16;}if(['pounce','peek','chase','parade'].includes(this.behavior))rig.position.y=Math.abs(Math.sin(t*7))*.25;if(this.behavior==='sneeze'){head.rotation.x=Math.sin(t*15)*.3;rig.position.y=Math.abs(Math.sin(t*10))*.11;}if(['nuzzle','follow'].includes(this.behavior)){head.rotation.z=Math.sin(t*5)*.22;eyes.forEach(e=>e.scale.y=.15);}}
 this.cat.position.copy(this.pos);this.cat.rotation.y=['wardrobe','adopt'].includes(this.mode)?.42+Math.sin(t*.4)*.08:this.face;if(this.petUntil>t){eyes.forEach(e=>e.scale.y=.13);head.rotation.z=Math.sin(t*8)*.1;}
 this.cat.updateMatrixWorld(true);this.cat.userData.mouth.getWorldPosition(this.carriedToy.position);this.cat.userData.top.getWorldPosition(this.leafHat.position);this.ducks.position.set(this.pos.x-1.1,.08,this.pos.z);this.ducks.children.forEach((d,i)=>d.position.y=Math.abs(Math.sin(t*7+i))*.035);
 if(this.mode==='free'&&this.stats.bond>=70&&this.idleCount>0)this.emit('gift-check');this.emitFrame();
 }
 emitFrame(){if(!this.cat)return;const labels=[];if(this.mode==='explore'&&this.outing){for(const s of this.outing.spots)if(!this.outing.found.includes(s.id))labels.push({id:s.id,...this.project(new THREE.Vector3(s.x,.85,s.z))});if(!this.outing.friendDone)labels.push({id:'friend',...this.project(new THREE.Vector3(2.5,1.65,-.8))});if(!this.outing.eventDone)labels.push({id:'event',...this.project(new THREE.Vector3(-2.35,.72,-.85))});}this.emit('frame',{labels,cat:this.project(this.cat.position.clone().add(new THREE.Vector3(0,1.5,0)))});}
}
