import {fitFurniture} from './furniture-layout.js';
import './style.css';
import {icon} from './icons.js';
import {BREEDS,OUTFITS,ACTIONS,SAVE_KEY,freshState,normalizeSave,applyAction,INGREDIENTS,FAVORITES,PERSONALITIES,FURNITURE,OUTFIT_COST,REGIONS,TREASURES,BONDS,bondLevel,reward,purchase,placeFurniture,serveRecipe,makeOuting,collectTreasure} from './state.js';
import {restartGame,previousGame,restoreGame} from './save-manager.js';
import {LivingWorld} from './living-world.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,saveOK=true;try{state=normalizeSave(JSON.parse(localStorage.getItem(SAVE_KEY)));}catch{state=freshState();}
let mode='adopt',selected=state.breed,homeTab='care',sound=false,audio,toastTimer,world,busy=false,activity=null,timer=null,raf=null,lastPet=0,session=null,outing=null,selectedIngredients=['fish'],bathPhase='scrub',bathValue=0,selectedFurniture='box',tvChannel=0,pendingSpot=null;
let giftChecked=false;const runId=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const save=()=>{state.updatedAt=Date.now();try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));$('#save-status').textContent='✓ 已保存小猫的日常';}catch{saveOK=false;$('#save-status').textContent='暂时无法保存';}if($('#wallet'))$('#wallet').textContent=`♡ ${state.hearts}`;};
const say=text=>{$('#bubble').textContent=text;};
const toast=text=>{clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3100);};
function tone(f=523,d=.13){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.8,audio.currentTime+d);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}}
function hearts(symbol='♡'){for(let i=0;i<6;i++){const e=document.createElement('span');e.className='particle';e.textContent=symbol;e.style.setProperty('--drift',`${(i-2.5)*25}px`);e.style.marginLeft=`${(i-2.5)*9}px`;e.style.animationDelay=`${i*.07}s`;$('#fx-layer').append(e);setTimeout(()=>e.remove(),2200);}}
function updateStats(){const el=$('#stats');el.hidden=!state.adopted;el.innerHTML=[['fullness','饱腹','#c58d65'],['clean','清洁','#78a9c7'],['mood','心情','#9dac78']].map(([key,label,color])=>`<div class="stat" data-stat="${key}" style="--stat-color:${color}">${label}<b>${state[key]}</b><div class="stat-track" role="meter" aria-label="${label}" aria-valuenow="${state[key]}" aria-valuemin="0" aria-valuemax="100"><i style="width:${state[key]}%"></i></div></div>`).join('');$('#wallet').hidden=!state.adopted;$('#wallet').textContent=`♡ ${state.hearts}`;if($('#bond-label'))$('#bond-label').textContent=`${bondLevel(state).name} · ${state.bond}`;}
function commit(next,celebrate=false){const prev=bondLevel(state);state=next;save();updateStats();world.syncState(state);if(celebrate){hearts();tone(720);}if(bondLevel(state).at>prev.at){toast(`关系升级：${bondLevel(state).name}！${bondLevel(state).hint}`);}}
function heading(kicker,title,desc=''){ $('#scene-kicker').textContent=kicker;$('#scene-title').textContent=title;$('#scene-description').textContent=desc;}
function shelf(html,cls=''){ $('#shelf').className=`shelf expanded-shelf ${cls}`;const steps=mode==='toy'?{wand:[['feather','晃晃羽毛'],['paw','抓住它'],['gift','集满 5 爪']],fetch:[['ball','抛小球'],['cat','叼回来'],['gift','送达 3 次']],hide:[['box','观察纸箱'],['search','找小猫'],['gift','找到 2 次']]}[session?.kind]:guides[mode];if(steps){const marker='</span></div>';const at=html.indexOf(marker);if(at>=0)html=html.slice(0,at+marker.length)+guide(steps)+html.slice(at+marker.length);}$('#shelf').innerHTML=html;}
const button=(id,label,symbol,extra='')=>`<button class="action-button" data-action="${id}" aria-label="${esc(label)}" ${extra}><span class="action-icon">${symbol?.startsWith('<')?symbol:esc(symbol||'✧')}</span><span>${esc(label)}</span></button>`;
const guide=(steps)=>`<div class="how-to" aria-label="玩法图解">${steps.map(([picture,label],i)=>`<div class="guide-step"><span>${icon(picture)}</span><small>${label}</small></div>${i<steps.length-1?'<i>›</i>':''}`).join('')}</div>`;
const guides={kitchen:[['feed','选食材'],['cat','尝一口'],['heart','发现最爱']],bath:[['sponge','搓泡泡'],['shower','冲干净'],['paw','香香完成']],tv:[['tv','选频道'],['cat','一起看'],['heart','收获陪伴']],map:[['map','选目的地'],['search','找宝物'],['gift','带回家']],portrait:[['hand','拖动看看'],['cat','摸摸脑袋'],['heart','看小表情']],wardrobe:[['wardrobe','挑一件'],['cat','试穿'],['heart','新造型']]};
const line=(text,progress=false)=>`<div class="shelf-line"><span id="action-status">${esc(text)}</span>${progress?'<span class="progress-track"><i></i></span>':''}<span id="bond-label">${bondLevel(state).name} · ${state.bond}</span></div>`;
function cleanup(){clearTimeout(timer);cancelAnimationFrame(raf);timer=null;busy=false;activity=null;pendingSpot=null;world.finishAction();world.clearExploration();$('#world-labels').replaceChildren();$('#bath-splash').classList.remove('show');session=null;outing=null;}
function scene(name,sceneName,title,kicker,desc=''){cleanup();mode=name;$('#app').dataset.mode=name;$('#app').className=`game-mode expansion-mode ${name==='wardrobe'?'wardrobe-mode':''}`;world.setScene(sceneName);$('#home').hidden=false;$('#scene-hotspot').hidden=true;$('#world-labels').hidden=name!=='explore';heading(kicker,title,desc);updateStats();}
try{world=new LivingWorld($('#world'),pet,openWardrobe,worldEvent);}catch(err){$('#loading').innerHTML='<span>☁</span><div>这台浏览器暂时没能打开 3D 场景。<br>请开启硬件加速，或换用较新的 Chrome / Safari 后刷新。</div>';console.error(err);throw err;}
const thumbs=world.thumbnails();
function selectBreed(id){if(state.adopted)return;selected=id;world.setCat(id,'none');const b=BREEDS.find(x=>x.id===id);say(b.quote);$('.shelf-caption strong').textContent=b.description;$$('.cat-option').forEach(btn=>{const yes=btn.dataset.breed===id;btn.classList.toggle('selected',yes);btn.setAttribute('aria-pressed',String(yes));btn.querySelector('.check').hidden=!yes;});tone(390);}
function showAdopt(){mode='adopt';$('#app').dataset.mode='adopt';$('#app').className='';$('#stats').hidden=true;$('#wallet').hidden=true;$('#home').hidden=true;$('#scene-hotspot').hidden=true;$('#world-labels').hidden=true;heading('初次见面，请多关照','想把哪只小可爱\n带回家？','选一只小猫，一起把日子过成喜剧。');$('#scene-title').style.whiteSpace='pre-line';$('#shelf').className='shelf adopt-shelf';$('#shelf').innerHTML=`<div class="shelf-caption"><span>挑一只，先打个招呼</span><strong></strong></div><div class="cat-options" role="group" aria-label="选择猫咪">${BREEDS.map(b=>`<button class="cat-option" data-breed="${b.id}" aria-label="选择${b.name}" aria-pressed="false"><img src="${thumbs[b.id]}" alt="${b.name}的三维外观"><span><strong>${b.name}</strong><small>${b.tag}</small></span><span class="check" hidden>✓</span></button>`).join('')}</div><form class="adopt-row" id="adopt-form"><label class="name-label">给它取个名字<input id="cat-name" maxlength="12" value="糯米" autocomplete="off" aria-label="小猫名字"></label><button class="primary" type="submit">♡ 带它回家</button><span class="adopt-note welcome-loot"><span>♡ 6 颗爱心</span><span>▣ 纸箱城堡</span></span></form>`;$$('[data-breed]').forEach(b=>b.onclick=()=>selectBreed(b.dataset.breed));$('#adopt-form').onsubmit=e=>{e.preventDefault();state={...freshState(),adopted:true,breed:selected,name:$('#cat-name').value.trim().slice(0,12)||'糯米',memories:['相遇的第一天：从此，家里多了一个小祖宗。']};world.setCat(state.breed,state.outfit);save();showHome();say('新家不错！先陪我玩，还是一起去探险？');hearts();};world.setScene('adopt');world.setMode('adopt');selectBreed(selected);}
function showHome(){scene('home','home',`${state.name}的甜梦小屋`,PERSONALITIES[state.breed].name,'猫咪会自己活动。点家具邀请它试一试。');world.setMode('free');world.syncState(state);$('#home').hidden=true;$('#scene-hotspot').hidden=false;renderHome();say('小屋巡逻准备中。陪玩、寻宝、布置，今天先做哪件？');$('#footer-note').textContent=saveOK?'本机自动保存 · 慢慢玩，随时回来':'请允许浏览器存储以保存进度';}
function renderHome(){const groups={care:[['feed','搭配猫饭',icon('feed')],['bath','泡泡洗澡',icon('bath')],['tv','一起追剧',icon('tv')],['explore','外出探险',icon('play')],['wardrobe','换衣服',icon('wardrobe')],['album','纪念册',icon('memory')]],play:[['wand','逗猫棒',icon('feather')],['fetch','抛球捡球',icon('ball')],['hide','纸箱捉迷藏',icon('box')],['call','叫名字','♫'],['nuzzle','蹭蹭','♡'],['explore','外出探险',icon('play')]],house:[['decorate','布置小屋',icon('box')],['collection','宝物收藏','✧'],['bond','感情成长','♡'],['wardrobe','换衣服',icon('wardrobe')],['album','纪念册',icon('memory')],['portrait','近看小猫',icon('cat')]]};shelf(`<div class="home-tabs" role="group" aria-label="玩法分类">${[['care','日常照顾'],['play','陪它玩'],['house','我们的小屋']].map(([id,name])=>`<button data-tab="${id}" aria-pressed="${id===homeTab}" class="${id===homeTab?'selected':''}">${name}</button>`).join('')}</div><div class="action-row">${groups[homeTab].map(([id,label,symbol])=>button(id,label,symbol)).join('')}</div>${line('一起玩赚爱心，装扮属于你们的小屋。')}`);$$('[data-tab]').forEach(b=>b.onclick=()=>{homeTab=b.dataset.tab;renderHome();});$$('[data-action]').forEach(b=>b.onclick=()=>dispatch(b.dataset.action));}
function dispatch(id){if(id==='portrait')openPortrait();if(id==='feed')openKitchen();if(id==='bath')openBath();if(id==='tv')openTV();if(id==='explore')openMap();if(id==='wardrobe')openWardrobe();if(id==='album')showAlbum();if(id==='collection')showCollection();if(id==='bond')showBond();if(id==='decorate')openDecorate();if(['wand','fetch','hide'].includes(id))openToy(id);if(id==='call'){if(state.bond<12){toast(`再增加 ${12-state.bond} 点亲密，它就能认出自己的名字啦。`);return;}world.callCat();say(`${state.name}，过来呀！`);}if(id==='nuzzle'){if(state.bond<35){toast(`亲密到 35 就能解锁蹭蹭，现在可以点小猫摸摸。`);return;}world.pose('nuzzle',4);say('蹭蹭专属人类，确认过味道，是自己家。');hearts();}}
function openToy(kind){const spec={wand:['逗猫棒追逐赛','拖动羽毛逗猫，抓到 5 次就完成。'],fetch:['小球快递员','点地面抛球，等小猫叼回来；完成 3 次。'],hide:['纸箱里藏着谁','观察哪只箱子在动，也可以听听呼噜声。']}[kind];scene('toy','home',spec[0],'一起动起来',spec[1]);session={kind,id:`${kind}-${runId()}`,count:0,goal:kind==='wand'?5:kind==='fetch'?3:2,done:false};world.setMode(kind);shelf(`<div class="activity-heading"><b>${spec[0]}</b><span>${spec[1]}</span></div><div class="paw-score" id="toy-score" aria-label="本轮完成进度"></div><div class="activity-controls" id="toy-controls"></div>${line('开始吧，小猫已经准备好了！',true)}`);renderToyControls();updateToyProgress();say(kind==='fetch'?'发货地址：你手里。运费：摸摸头。':kind==='hide'?'本喵藏得很隐蔽。除了呼噜声有点大。':'这根羽毛，今天必须拿下！');}
function renderToyControls(){if(!session)return;const {kind,done}=session;if(done){$('#toy-controls').innerHTML='<button class="primary" id="toy-again">再玩一轮</button><button class="soft-button" id="toy-home">带着爱心回家</button>';$('#toy-again').onclick=()=>openToy(kind);$('#toy-home').onclick=showHome;return;}if(kind==='wand'){$('#toy-controls').innerHTML='<button class="primary" id="wiggle">晃晃逗猫棒</button><span class="control-tip">也可以在场景中拖动羽毛</span>';$('#wiggle').onclick=()=>world.wiggleWand();}
 if(kind==='fetch'){$('#toy-controls').innerHTML='<button class="primary" id="throw-ball">抛出小球</button><span class="control-tip">也可以点地面选择落点</span>';$('#throw-ball').onclick=()=>world.throwBall(session.count%2? -2.2:2.2,.55);}
 if(kind==='hide'){$('#toy-controls').innerHTML=`${['左边箱子','中间箱子','右边箱子'].map((s,i)=>`<button class="soft-button" data-box="${i}">${s}</button>`).join('')}<button class="hint-button" id="listen">听听呼噜声</button>`;$$('[data-box]').forEach(b=>b.onclick=()=>world.chooseBox(Number(b.dataset.box)));$('#listen').onclick=()=>{say(`嘘……呼噜声从${world.hideHint()}箱子传来！`);tone(250,.3);};}}
function updateToyProgress(){if(!session)return;$('#toy-score').innerHTML=Array.from({length:session.goal},(_,i)=>`<span class="${i<session.count?'earned':''}">${icon('paw')}</span>`).join('');$('#action-status').textContent=`${session.kind==='hide'?'找到':session.kind==='fetch'?'捡回':'抓到'} ${session.count} / ${session.goal} 次`;$(' .progress-track>i').style.width=`${Math.min(100,session.count/session.goal*100)}%`;}
function toyPoint(){if(!session||session.done)return;session.count++;updateToyProgress();hearts('✧');tone(600);if(session.count>=session.goal){session.done=true;commit(reward(state,{id:session.id,hearts:3,bond:6,stat:'mood',amount:14,memory:{wand:'逗猫棒首胜：猫抓到了羽毛，也抓到了快乐。',fetch:'第一次叼球回来：小球快递，货到摸头。',hide:'第一次捉迷藏：纸箱保密，呼噜泄密。'}[session.kind]}),true);world.setMode('toy-done');say('任务完成！爱心 +3，亲密 +6。再来一局也奉陪！');$('#action-status').textContent='完成！爱心 +3 · 亲密 +6';renderToyControls();}else if(session.kind==='hide'){$('#toy-controls').innerHTML='<button class="primary" id="next-hide">再藏一次</button>';$('#next-hide').onclick=()=>{world.newHideRound();renderToyControls();};say('被发现了！刚才一定是纸箱告的密。');}}
function openKitchen(){scene('kitchen','home','今天的小猫私房菜','两种食材，随你搭配','发现最爱口味，获得额外爱心。');world.setMode('meal');world.bowl.visible=true;world.food.visible=false;selectedIngredients=['fish'];shelf(`<div class="activity-heading"><b>选 1–2 种食材</b><span id="taste-note">${tasteHint()}</span></div><div class="ingredient-row">${INGREDIENTS.map(i=>`<button class="ingredient ${selectedIngredients.includes(i.id)?'selected':''}" data-ingredient="${i.id}" aria-pressed="${selectedIngredients.includes(i.id)}"><span>${i.icon}</span>${i.name}</button>`).join('')}<button class="primary" id="serve">开饭啦</button></div>${line('猫饭配方会记在纪念册里。')}`);$$('[data-ingredient]').forEach(b=>b.onclick=()=>{if(busy)return;const id=b.dataset.ingredient;if(selectedIngredients.includes(id))selectedIngredients=selectedIngredients.filter(x=>x!==id);else if(selectedIngredients.length<2)selectedIngredients.push(id);else{toast('一碗放两种就很丰盛啦，先取消一种再换。');return;}$$('[data-ingredient]').forEach(x=>{const selected=selectedIngredients.includes(x.dataset.ingredient);x.classList.toggle('selected',selected);x.setAttribute('aria-pressed',String(selected));});$('#serve').disabled=!selectedIngredients.length;});$('#serve').onclick=serveMeal;say('主厨你好，我负责认真吃和认真点评。');}
function tasteHint(){const fav=FAVORITES[state.breed];return state.discoveredFoods.includes(fav)?`已发现最爱：${INGREDIENTS.find(i=>i.id===fav).name}`:'它的最爱还是秘密，试着发现吧。';}
function serveMeal(){if(busy||!selectedIngredients.length)return;busy=true;const token=`meal-${runId()}`,recipe=[...selectedIngredients];$('#serve').disabled=true;$$('[data-ingredient]').forEach(b=>b.disabled=true);world.startAction('feed');say('让我先用鼻子投个票……');$('#action-status').textContent='认真品尝中…';timer=setTimeout(()=>{if(mode!=='kitchen')return;const result=serveRecipe(state,recipe,token);commit(result.state,true);world.finishAction();world.pose(result.liked?'pounce':'sniff',3);busy=false;say(result.liked?'就是这个味！喜欢到耳朵都要起飞了。爱心 +2！':'这碗也不错！最爱口味还等着你发现。爱心 +1。');$('#taste-note').textContent=tasteHint();$('#action-status').textContent=result.liked?'发现最爱口味 · 饱腹 +26 · 亲密 +7':'吃饱啦 · 饱腹 +26 · 亲密 +5';$('#serve').textContent='再做一碗';$('#serve').disabled=false;$$('[data-ingredient]').forEach(b=>b.disabled=false);},3200);}
function openBath(){scene('bath','bath','把小猫洗成香香云','动手泡泡浴','拖海绵在猫咪身上搓，再用花洒冲干净。');world.setMode('scrub');bathPhase='scrub';bathValue=0;activity=`bath-${runId()}`;renderBath();say('耳朵可以湿，尊严……算了，泡泡好玩。');}
function renderBath(){shelf(`<div class="activity-heading"><b id="bath-step">${bathPhase==='scrub'?'第一步：搓出泡泡':'第二步：冲掉泡泡'}</b><span>在小猫身上拖动工具，或点下面按钮</span></div><div class="activity-controls"><button class="primary" id="bath-work">${bathPhase==='scrub'?'搓一搓':'冲一冲'}</button><button class="soft-button" id="bath-next" hidden>拿起花洒</button></div>${line('慢慢来，小猫不赶时间。',true)}`);$('#bath-work').onclick=()=>bathStroke(12);$('#bath-next').onclick=()=>{bathPhase='rinse';bathValue=0;world.setMode('rinse');world.bathProgress(0,'rinse');renderBath();say('准备冲水！泡泡胡子申请保留失败。');};}
function bathStroke(amount){if(mode!=='bath'||bathPhase==='done'||bathValue>=100)return;bathValue=Math.min(100,bathValue+amount);world.bathProgress(bathValue/100,bathPhase);$('.progress-track>i').style.width=`${bathValue}%`;$('#action-status').textContent=`${bathPhase==='scrub'?'泡泡覆盖':'冲洗进度'} ${Math.floor(bathValue)}%`;if(bathValue>=100){if(bathPhase==='scrub'){$('#bath-next').hidden=false;$('#bath-work').disabled=true;say('泡泡足够啦，拿花洒把它们冲走。');}else{bathPhase='done';$('#bath-work').disabled=true;commit(applyAction(state,'bath',activity),true);world.setMode('bath-done');world.pose('sneeze',3);$('#bath-splash').classList.add('show');say('甩甩毛！好了，现在你也洗过澡了。');$('#action-status').textContent='香香完成 · 清洁 +35 · 爱心 +1';timer=setTimeout(()=>$('#bath-splash').classList.remove('show'),2000);}}}
function openTV(){scene('tv','tv','今天追哪一档？','喵喵家庭影院','切换频道，看看小猫喜欢什么。');world.setMode('tv');world.setTVChannel(0);tvChannel=0;shelf(`<div class="activity-heading"><b>猫咪遥控器</b><span>选择频道，陪它看完一小段</span></div><div class="activity-controls">${['鱼鱼频道','蝴蝶纪录片','鸟鸟音乐会'].map((s,i)=>`<button class="soft-button channel ${i===0?'selected':''}" data-channel="${i}"><span>${['🐟','🦋','🐦'][i]}</span>${s}</button>`).join('')}<button class="primary" id="watch">一起看</button></div>${line('没有广告，只有猫的弹幕。',true)}`);$$('[data-channel]').forEach(b=>b.onclick=()=>{if(busy)return;tvChannel=Number(b.dataset.channel);$$('[data-channel]').forEach(x=>x.classList.toggle('selected',x===b));say(['这条鱼演技不错，就是游不出来。','蝴蝶请别乱飞，猫的眼睛跟不上了！','跟唱失败，但呼噜声已经加入合唱。'][tvChannel]);world.setTVChannel(tvChannel);});$('#watch').onclick=()=>{if(busy)return;busy=true;const id=`tv-${runId()}`;world.startAction('tv');$$('[data-channel],#watch').forEach(b=>b.disabled=true);const begin=performance.now();const tick=()=>{if(mode!=='tv')return;$('.progress-track>i').style.width=`${Math.min(100,(performance.now()-begin)/48)}%`;if(busy)raf=requestAnimationFrame(tick);};tick();timer=setTimeout(()=>{if(mode!=='tv')return;busy=false;world.finishAction();commit(applyAction(state,'tv',id),true);say('追完啦！猫决定把节目给五个爪爪好评。');$('#action-status').textContent='陪伴完成 · 心情 +23 · 爱心 +1';$$('[data-channel],#watch').forEach(b=>b.disabled=false);},4800);};say('遥控器交给你，沙发归本喵。');}
function openMap(){scene('map','park','今天去哪里散步？','把小世界走大一点','每次出发都有不同宝物与小插曲。');world.setMode('map');shelf(`<div class="activity-heading"><b>选一个目的地</b><span>点地面走路 · 调查闪光点 · 认识猫朋友</span></div><div class="region-row">${REGIONS.map(r=>`<button class="region-button" data-region="${r.id}"><span>${r.icon}</span><b>${r.name}</b><small>已收集 ${state.collection.filter(id=>TREASURES.find(t=>t.id===id)?.region===r.id).length} / 4</small></button>`).join('')}</div>${line('每次找到 3 件宝物，还会获得一份探险奖励。')}`);$$('[data-region]').forEach(b=>b.onclick=()=>startExploration(b.dataset.region));say('出门记得带上好奇心，饭碗就先不带了。');}
function startExploration(region){scene('explore',region,REGIONS.find(r=>r.id===region).name,'小小探险家',REGIONS.find(r=>r.id===region).intro);state.journeys++;save();outing=makeOuting(region,state.journeys);world.setMode('explore');world.setupExploration(outing);shelf(`<div class="explore-bar"><b id="explore-count"><span class="treasure-pips"><i>✦</i><i>✦</i><i>✦</i></span> 0 / 3</b><button class="soft-button" id="explore-hint">找最近的宝物</button><button class="soft-button" id="change-region">换个地方</button></div><div class="explore-controls"><div class="direction-pad" aria-label="移动猫咪"><button data-move="up" aria-label="向前走">↑</button><button data-move="left" aria-label="向左走">←</button><button data-move="down" aria-label="向后走">↓</button><button data-move="right" aria-label="向右走">→</button></div><span>点地面走路 · 点问号调查<br>也可用方向键 / WASD</span></div>${line('找到宝物，交到朋友，再带一段故事回家。')}`);$('#explore-hint').onclick=()=>{const spot=outing.spots.filter(s=>!outing.found.includes(s.id)).sort((a,b)=>Math.hypot(a.x-world.pos.x,a.z-world.pos.z)-Math.hypot(b.x-world.pos.x,b.z-world.pos.z))[0];if(spot)visitSpot(spot.id);else say('宝物都找到啦，再和猫朋友打个招呼吧。');};$('#change-region').onclick=openMap;$$('[data-move]').forEach(b=>b.onclick=()=>moveDirection(b.dataset.move));renderMarkers();say(REGIONS.find(r=>r.id===region).intro);}
function renderMarkers(){if(!outing)return;$('#world-labels').innerHTML=`${outing.spots.filter(s=>!outing.found.includes(s.id)).map((s,i)=>`<button class="world-marker" data-spot="${s.id}" aria-label="调查宝物${i+1}"><b>?</b><span>调查</span></button>`).join('')}${!outing.friendDone?'<button class="world-marker friend-marker" data-spot="friend" aria-label="和猫朋友打招呼"><b>♡</b><span>猫朋友</span></button>':''}${!outing.eventDone?'<button class="world-marker event-marker" data-spot="event" aria-label="看看奇怪的动静"><b>!</b><span>小插曲</span></button>':''}`;$$('[data-spot]').forEach(b=>b.onclick=()=>visitSpot(b.dataset.spot));}
function visitSpot(id){if(mode!=='explore'||!outing)return;if(id==='friend'&&outing.friendDone||id==='event'&&outing.eventDone||outing.found.includes(id))return;const spot=id==='friend'?{x:2.05,z:-.35}:id==='event'?{x:-2.15,z:-.6}:outing.spots.find(s=>s.id===id);if(!spot)return;pendingSpot=id;say('收到！小爪爪正在赶往现场。');world.moveTo(spot.x,spot.z,()=>{if(mode!=='explore'||pendingSpot!==id)return;pendingSpot=null;arriveSpot(id);});}
function arriveSpot(id){if(!outing)return;world.pose(id==='event'?outing.event.pose:'sniff',3);if(id==='friend'){const isNew=!state.friends.includes(outing.region);outing.friendDone=true;let n=reward(state,{id:`${outing.id}-friend`,hearts:1,bond:3,memory:isNew?`认识了${REGIONS.find(r=>r.id===outing.region).name}的猫朋友：先碰鼻子，再交换呼噜。`:undefined});n={...n,friends:[...new Set([...n.friends,outing.region])]};commit(n,true);say('碰鼻子，交朋友！它推荐你去看看附近的闪光点。');}else if(id==='event'){outing.eventDone=true;commit(reward(state,{id:`${outing.id}-event`,hearts:1,bond:3,memory:`${outing.event.title}：${outing.event.text}`}),true);say(outing.event.text);world.pose(outing.event.pose,5);}else{const result=collectTreasure(state,outing,id);outing=result.outing;commit(result.state,true);world.hideSpot(id);say(`找到${TREASURES.find(t=>t.id===id).name}！猫：这个必须带回家。`);$('#explore-count').innerHTML=`<span class="treasure-pips">${[0,1,2].map(i=>`<i class="${i<outing.found.length?'found':''}">✦</i>`).join('')}</span> ${outing.found.length} / 3`;if(outing.found.length===3&&!outing.finished){outing.finished=true;commit(reward(state,{id:`${outing.id}-complete`,hearts:3,bond:5,stat:'mood',amount:15,memory:'第一次寻宝大成功：兜里装着宝物，心里装着快乐。'}),true);state.fullness=Math.max(10,state.fullness-6);state.clean=Math.max(10,state.clean-9);save();updateStats();$('#action-status').textContent='寻宝完成！额外爱心 +3 · 还可以继续散步';toast('三件宝物到手！额外获得 3 颗爱心。');}}
 world.outing=outing;renderMarkers();}
function moveDirection(dir){if(mode!=='explore')return;pendingSpot=null;const delta={up:[0,-.55],down:[0,.55],left:[-.55,0],right:[.55,0]}[dir];world.moveTo(Math.max(-3.2,Math.min(3.2,world.pos.x+delta[0])),Math.max(-1.9,Math.min(2.3,world.pos.z+delta[1])));}
function openDecorate(){scene('decorate','home','把小屋摆成喜欢的样子','家里的每一件，都能玩','选家具，点地面摆放；也可以直接拖动家具。');world.setMode('decorate');world.syncState(state);selectedFurniture=state.furniture[0]?.id||'box';world.selectFurniture(selectedFurniture);renderDecorate();say('家具你来摆，使用权本喵全包。');}
function renderDecorate(){shelf(`<div class="activity-heading"><b>爱心小商店 · ♡ ${state.hearts}</b><span>已经拥有的家具可以自由移动</span></div><div class="furniture-row">${FURNITURE.map(f=>`<button class="furniture-option ${selectedFurniture===f.id?'selected':''}" data-furniture="${f.id}" aria-label="${state.ownedFurniture.includes(f.id)?'摆放':'购买'}${f.name}"><span>${f.icon}</span><b>${f.name}</b><small>${state.ownedFurniture.includes(f.id)?'已拥有':`♡ ${f.cost}`}</small></button>`).join('')}</div><div class="placement-row"><button class="soft-button" id="furniture-rotate">旋转</button><button class="soft-button" id="furniture-left">往左一点</button><button class="soft-button" id="furniture-right">往右一点</button><button class="primary" id="furniture-done">摆好了</button></div>${line(`正在摆放：${FURNITURE.find(f=>f.id===selectedFurniture)?.name||'纸箱城堡'}`)}`);$$('[data-furniture]').forEach(b=>b.onclick=()=>{const id=b.dataset.furniture;const result=purchase(state,'furniture',id);if(!result.ok){toast(result.reason);return;}state=result.state;if(!state.furniture.some(f=>f.id===id)){const empty=[[0,1.65],[-2.7,1.55],[1.1,2.2],[3.1,.3],[-1.4,.4]].find(([x,z])=>state.furniture.every(f=>f.id==='rug'||id==='rug'||Math.hypot(f.x-x,f.z-z)>.9))||[0,1.65];state=placeFurniture(state,id,...empty,0);}state.furniture=fitFurniture(state.furniture);selectedFurniture=id;save();world.syncState(state);world.selectFurniture(id);renderDecorate();say(`${FURNITURE.find(f=>f.id===id).name}准备好了，点地面把它摆过去。`);});$('#furniture-rotate').onclick=()=>{const f=state.furniture.find(f=>f.id===selectedFurniture);if(f)world.placeSelected(f.x,f.z,f.rotation+Math.PI/4);};for(const [id,d]of [['furniture-left',-.35],['furniture-right',.35]])$('#'+id).onclick=()=>{const f=state.furniture.find(f=>f.id===selectedFurniture);if(f)world.placeSelected(f.x+d,f.z);};$('#furniture-done').onclick=()=>{const id=selectedFurniture;showHome();world.useFurniture(id);};}
function openPortrait(){scene('portrait','adopt',`${state.name}的可爱特写`,'靠近一点，看见小表情','拖动转视角，看看眼睛和小爪子。');world.setMode('portrait');shelf(`<div class="activity-heading"><b>小猫专属镜头</b><span>房间里保持自然比例，近景看清每个细节。</span></div><div class="activity-controls"><button class="soft-button" id="portrait-pet">摸摸小脑袋</button><button class="soft-button" id="portrait-head">歪歪头</button><button class="primary" id="portrait-home">回到小屋</button></div>${line('慢慢转动视角，和小猫对视一会儿。')}`);$('#portrait-pet').onclick=()=>{world.pet();say('呼噜噜……这个角度也很可爱。');};$('#portrait-head').onclick=()=>{world.pose('nuzzle',3);say('你在看我吗？那我也看看你。');};$('#portrait-home').onclick=showHome;say('靠近一点点，眼睛里都是你。');}
function openWardrobe(){if(!state.adopted)return;scene('wardrobe','wardrobe','今天，穿哪件？','小猫的秘密衣柜','爱心可以解锁新造型。');world.setMode('wardrobe');renderWardrobe();say('今天要穿出可爱，还是穿出饭量？');}
function renderWardrobe(){shelf(`<div class="activity-heading"><b>我的衣柜</b><span>可用爱心 ♡ ${state.hearts}</span></div><div class="wardrobe-row">${OUTFITS.map(o=>`<button data-outfit="${o.id}" class="action-button outfit-button ${state.outfit===o.id?'selected':''}" aria-label="${state.ownedOutfits.includes(o.id)?'穿上':'解锁'}${o.name}" aria-pressed="${state.outfit===o.id}"><span class="action-icon">${o.icon}</span><span>${o.name}</span><small>${state.ownedOutfits.includes(o.id)?'已拥有':`♡ ${OUTFIT_COST[o.id]}`}</small></button>`).join('')}</div>${line('点一下就穿好 · 用两侧箭头看新造型')}`);$$('[data-outfit]').forEach(b=>b.onclick=()=>{const result=purchase(state,'outfit',b.dataset.outfit);if(!result.ok){toast(result.reason);return;}state={...result.state,outfit:b.dataset.outfit};world.setCat(state.breed,state.outfit);world.pos.set(0,.32,.25);save();renderWardrobe();say(OUTFITS.find(o=>o.id===state.outfit).hint+'。今天的可爱也超标了。');hearts('✧');});}
function pet(){if(!state.adopted){world.pet();say('摸摸可以，领回家更可以。');return;}if(!['home','wardrobe'].includes(mode))return;world.pet();if(Date.now()-lastPet>3000){lastPet=Date.now();commit(reward(state,{bond:1,stat:'mood',amount:2}));hearts();tone(570);}say(state.bond>=35?'蹭蹭你！本喵已经认定这位人类。':['呼噜呼噜…已切换成小马达。','再摸一下？再一下也行。','你的手被本喵征用了。'][Math.floor(Math.random()*3)]);}
function showDialog(title,summary,html){$('#album h2').textContent=title;$('#album-summary').textContent=summary;$('#memory-list').innerHTML=html;$('#album').showModal();world.setPaused(true);}
function showAlbum(){showDialog('我们的喵喵纪念册',`${state.name}和你：${bondLevel(state).name}，亲密 ${state.bond}。`,`<div class="memory-stamps"><span>${icon('cat')}<b>${state.visits}</b><small>次回家</small></span><span>${icon('feed')}<b>${state.recipes.length}</b><small>种猫饭</small></span><span>${icon('map')}<b>${state.journeys}</b><small>次探险</small></span></div><div class="memory-book">${state.memories.map((m,i)=>`<article class="memory-ticket"><span class="memory-seal">${icon(['cat','heart','paw','gift','map'][i%5])}</span><div><small>回忆 ${String(i+1).padStart(2,'0')}</small><p>${esc(m)}</p></div></article>`).join('')}</div>`);}
function showCollection(){showDialog('小猫的宝物抽屉',`发现 ${state.collection.length} / ${TREASURES.length} 件宝物，认识 ${state.friends.length} / 3 位猫朋友。`,`<div class="collection-grid">${TREASURES.map(t=>`<div class="collection-item ${state.collection.includes(t.id)?'found':''}"><span>${state.collection.includes(t.id)?t.icon:'?'}</span><b>${state.collection.includes(t.id)?t.name:'还没发现'}</b><small>${REGIONS.find(r=>r.id===t.region).name}</small></div>`).join('')}</div>`);}
function showBond(){showDialog('从小室友，到一家人',`现在是「${bondLevel(state).name}」，亲密 ${state.bond}。`,`<div class="bond-trail">${BONDS.map((t,i)=>`<article class="bond-stop ${state.bond>=t.at?'unlocked':''}"><span>${icon(['cat','paw','heart','gift'][i%4])}</span><div><small>${state.bond>=t.at?'已解锁':`再积累 ${t.at-state.bond} 点亲密`}</small><b>${t.name}</b><p>${t.hint}</p></div><em>${state.bond>=t.at?'✓':t.at}</em></article>`).join('')}</div>`);}
function worldEvent(type,data){if(!world)return;if(type==='input-mode'){$('.view-controls span').textContent={wand:'拖动羽毛 · 箭头转视角',fetch:'点地面抛球 · 箭头转视角',hide:'点箱子找猫 · 箭头转视角',scrub:'在猫身上拖海绵',rinse:'在猫身上拖花洒',decorate:'拖家具摆放 · 箭头转视角',explore:'点地面走路 · 箭头转视角'}[data.mode]||'拖动看看 · 点猫咪摸摸';return;}if(type==='placement-blocked'){toast('这里放不下啦，给小猫和家具留点空间吧。');return;}if(type==='frame'){for(const label of data.labels){const el=$(`[data-spot="${label.id}"]`);if(el){el.style.left=`${label.x}px`;el.style.top=`${label.y}px`;}}return;}if(type==='behavior'&&mode==='home')say(data.text);if(type==='arrived-call'&&mode==='home'){say('听到名字就来了！小爪爪比嘴还诚实。');hearts();}if(type==='wand-catch'&&mode==='toy'&&session?.kind==='wand'){toyPoint();if(!session.done)say(session.count%2?'抓到了！再换个位置，本喵还能追！':'差点刹不住车。没事，猫的事不算出糗。');}if(type==='ball-thrown'&&$('#throw-ball')){$('#throw-ball').disabled=true;say('小球已发射，快递喵出动！');}if(type==='fetch-return'&&session?.kind==='fetch'){toyPoint();if($('#throw-ball'))$('#throw-ball').disabled=false;if(!session.done)say('签收一下！这次运费是摸摸头。');}if(type==='hide-found'&&session?.kind==='hide')toyPoint();if(type==='hide-miss')say('这个箱子空空的。再看看哪个箱子在偷偷动。');if(type==='bath-stroke')bathStroke(data.amount);if(type==='visit-spot')visitSpot(data.id);if(type==='select-furniture'&&mode==='decorate'){selectedFurniture=data.id;$$('[data-furniture]').forEach(b=>b.classList.toggle('selected',b.dataset.furniture===data.id));$('#action-status').textContent=`正在摆放：${FURNITURE.find(f=>f.id===data.id).name}`;}if(type==='place'&&mode==='decorate'){state=placeFurniture(state,data.id,data.x,data.z,data.rotation);save();}if(type==='gift-check'&&!giftChecked&&mode==='home'){giftChecked=true;const today=new Date().toLocaleDateString('en-CA');if(state.lastGiftDay!==today){commit({...reward(state,{id:`gift-${today}`,hearts:3,memory:'第一次收到小猫礼物：它把最宝贝的小东西叼给了你。'}),lastGiftDay:today},true);world.pose('gift',5);say('小猫叼来一份礼物：这颗爱心，只送给最喜欢的人。爱心 +3！');}}}
$('#album-done').onclick=()=>$('#album').close();$('#album').addEventListener('click',e=>{if(e.target===$('#album')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('#home').onclick=()=>{if(busy||(mode==='bath'&&bathPhase!=='done'))toast('先回家休息，未完成的这次照顾不会发奖励。');showHome();};$('#scene-hotspot').onclick=openWardrobe;$('#rotate-left').onclick=()=>world.rotate(-1);$('#rotate-right').onclick=()=>world.rotate(1);$('#sound').onclick=()=>{sound=!sound;$('.sound-off').hidden=sound;$('#sound').setAttribute('aria-label',sound?'关闭音效':'开启音效');$('#sound').title=sound?'关闭音效':'开启音效';tone(660);toast(sound?'轻轻的音效已开启':'音效已关闭');};
document.addEventListener('keydown',e=>{if(mode!=='explore'||document.querySelector('dialog[open]')||['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;const dir={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'}[e.key];if(dir){e.preventDefault();moveDirection(dir);}});

function pauseForDialog(){world.setPaused(!!document.querySelector('dialog[open]'));}
for(const dialog of $$('dialog'))dialog.addEventListener('close',pauseForDialog);
function openSettings(){
 $('#restore-save').hidden=!previousGame(localStorage);$('#settings').showModal();world.setPaused(true);
}
$('#settings-open').onclick=openSettings;
$('#settings-close').onclick=$('#settings-done').onclick=()=>$('#settings').close();
$('#camera-reset').onclick=()=>{world.resetCamera();$('#settings').close();toast('已恢复默认视角');};
$('#restart-open').onclick=()=>{$('#settings').close();$('#restart-confirm').showModal();world.setPaused(true);};
$('#restart-cancel').onclick=()=>$('#restart-confirm').close();
$('#restart-confirm-button').onclick=()=>{
 try{const next=restartGame(localStorage,state);cleanup();state=next;selected=state.breed;homeTab='care';giftChecked=false;lastPet=0;selectedIngredients=['fish'];world.syncState(state);$('#restart-confirm').close();save();showAdopt();toast('新的故事开始了，选一只小猫吧。');}
 catch{toast('暂时无法保存新进度，原来的小猫还在。');}
};
$('#restore-save').onclick=()=>{
 try{const previous=restoreGame(localStorage);if(!previous)return;cleanup();state=previous;selected=state.breed;giftChecked=false;world.setCat(state.breed,state.outfit);world.syncState(state);$('#settings').close();save();showHome();toast('重开前的小猫和进度已恢复');}
 catch{toast('暂时无法恢复，请检查浏览器存储空间。');}
};

state.furniture=fitFurniture(state.furniture);world.setCat(state.breed,state.outfit);world.syncState(state);if(state.adopted){state.visits++;save();showHome();}else showAdopt();$('#loading').remove();
setInterval(()=>{if(!state.adopted||document.hidden||busy||mode!=='home')return;commit({...state,fullness:Math.max(10,state.fullness-1),clean:Math.max(10,state.clean-1),mood:Math.max(10,state.mood-1)});},90000);
window.addEventListener('pagehide',()=>{if(state.adopted)save();});
window.__miaow={inspect:()=>({state:structuredClone(state),mode,busy,session,outing,world:world.inspect()})};
